development:
  adapter: mysql
  database: rheet_development
  username: root
  password: password

production:
  adapter: mysql
  database: rheet_production
  username: root
  password: password

test:
  adapter: mysql
  database: rheet_test
  username: root
  password: password

