development:
  adapter: mysql
  database: rheet_development
  username: root
  password: password

demo:
  adapter: mysql
  database: rheet_demo
  username: root
  password: password

production:
  adapter: mysql
  database: rheet_production
  username: root
  password: password
